name: Trigger auto deployment for ca-customerapi

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/ca-customerapi-AutoDeployTrigger-8ccb5c4c-0a47-4a6b-a918-b24707b2f96f.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: acrhapiops.azurecr.io
          username: ${{ secrets.CACUSTOMERAPI_REGISTRY_USERNAME }}
          password: ${{ secrets.CACUSTOMERAPI_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: acrhapiops.azurecr.io/ca-customerapi:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CACUSTOMERAPI_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n ca-customerapi -g rg-hapiops --server acrhapiops.azurecr.io --username  ${{ secrets.CACUSTOMERAPI_REGISTRY_USERNAME }} --password ${{ secrets.CACUSTOMERAPI_REGISTRY_PASSWORD }}
            az containerapp update -n ca-customerapi -g rg-hapiops --image acrhapiops.azurecr.io/ca-customerapi:${{ github.sha }}
